package frc.robot.subsystems.drive;

/**
 * Sim-physics + teleop tunables for the swerve drive.
 *
 * <p>Module geometry, gear ratios, CANcoder offsets, gains, and CAN IDs all live in {@link
 * frc.robot.generated.TunerConstants} (generated by Tuner X). The only things here are the maple-sim
 * physics estimates (used to build the simulated drivetrain) and the teleop joystick deadband.
 */
public final class DriveConstants {
  private DriveConstants() {}

  // ---- maple-sim physics (simulation only; estimates — adjust to your real robot) ----
  public static final double ROBOT_MASS_KG = 50.0;
  public static final double BUMPER_SIZE_M = 0.7; // square footprint incl. bumpers
  public static final double WHEEL_COF = 1.2;
  // (wheel radius + gear ratios for the sim module come from TunerConstants, so the maple-sim physics
  // stays consistent with the odometry path — see RobotContainer's SwerveModuleSimulationConfig.)

  // ---- Teleop ----
  public static final double JOYSTICK_DEADBAND = 0.1;
}
